from .base import DomainError


class EmailVerificationObjectUsedError(DomainError): ...

class EmailVerificationObjectExpiredError(DomainError): ...


class EmailVerificationTokenMismatchError(DomainError): ...
