

services:

#  auth-service:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      ports:
#        - "8000:8000"
#      volumes:
#        - .:/auth
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=${SERVER_MODE}
    ports:
      - "5050:80"
    depends_on:
      - pg
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"